services:
  dempp:
    build:
      context: .
    container_name: run-dempp  
    volumes:
      - ./demo:/workspace/demo
      - ./data:/workspace/data
    environment:
      - PYTHONPATH=/workspace
    working_dir: /workspace
    tty: true
