name: dempp

services:
  dempp:
    build:
      context: .
    container_name: run-dempp  
    volumes:
      - $HOME:/workspace
    working_dir: /workspace
    tty: true
    ports:
      - 8888:8888